version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: kn-algo
    restart: always
    environment:
      POSTGRES_DB: algo-db
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"

volumes:
  db_data:
