package algo.module;

import jakarta.persistence.CascadeType;
import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderColumn;
import jakarta.persistence.Table;
import java.util.ArrayList;
import java.util.List;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** JPA entity representing a single project with translations and images. */
@Entity
@Table(name = "projects")
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Project {

  /** Max length of persisted enum name. */
  public static final int STATUS_L = 30;

  /** Max length of a single image URL. */
  public static final int IMAGE_URL_L = 500;

  /** Primary key generated by the database. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @EqualsAndHashCode.Include
  private Long projectId;

  /** Project section/category used by frontend (completed vs upcoming). */
  @Enumerated(EnumType.STRING)
  @Column(name = "status", nullable = false, length = STATUS_L)
  private ProjectType status;

  /**
   * Optional ordering field used for deterministic UI ordering.
   *
   * <p>Lower values appear first.</p>
   */
  @Column(name = "display_order")
  private Integer displayOrder;

  /** Ordered list of image URLs for the project. */
  @ElementCollection
  @CollectionTable(name = "project_images", joinColumns = @JoinColumn(name = "project_id"))
  @OrderColumn(name = "image_order")
  @Column(name = "image_url", length = IMAGE_URL_L)
  private final List<String> images = new ArrayList<>();

  /** Localized translations of this project. */
  @OneToMany(mappedBy = "project", cascade = CascadeType.ALL, orphanRemoval = true)
  @Setter(AccessLevel.NONE)
  private final List<ProjectTranslation> translations = new ArrayList<>();

  /**
   * Adds a translation and sets the back-reference.
   *
   * @param translation translation entity
   */
  public void addTranslation(final ProjectTranslation translation) {
    translations.add(translation);
    translation.setProject(this);
  }

  /** Clears all translations from this project. */
  public void clearTranslations() {
    translations.clear();
  }
}
