package algo.module;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * JPA entity representing a single project record.
 *
 * <p>Mapped to the {@code projects} table and stores the project type, image URLs, title, and full
 * description.
 */
@Entity
@Table(name = "projects")
@NoArgsConstructor
public class ProjectModule {
  /** Maximum length for the {@code projectType} enum value stored as text. */
  public static final int PROJECT_TYPE_L = 50;

  /** Maximum length for the project title. */
  public static final int PROJECT_TITLE_L = 100;

  /** Maximum length for the full project description. */
  public static final int PROJECT_DESC_L = 1000;

  /** Primary key generated by the database. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @EqualsAndHashCode.Include
  private Long projectId;

  /** Project category/type saved as enum name. */
  @Enumerated(EnumType.STRING)
  @Column(name = "projects", nullable = false, length = PROJECT_TYPE_L)
  private ProjectType projectType;

  /** Comma-separated or serialized image URLs related to the project. */
  @Column(name = "image_urls", nullable = false)
  private String imageUrls;

  /** Project title shown in listings and details. */
  @Column(name = "title", nullable = false, length = PROJECT_TITLE_L)
  private String title;

  /** Full project description/content. */
  @Column(name = "description", nullable = false, length = PROJECT_DESC_L)
  private String description;
}
